[package]
name = "muninn-index"
version = "0.2.2"
edition = "2021"

[[bin]]
name = "muninn-index"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
muninn-core = { path = "../core" }
sqlx = { workspace = true }
uuid = { workspace = true }
ignore = "0.4"
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
futures = { workspace = true }
notify = "6"

[dev-dependencies]
tempfile = "3"
