[package]
name = "muninn"
version = "0.1.16"
edition = "2021"

[[bin]]
name = "muninn"
path = "src/main.rs"

[dependencies]
muninn-core = { path = "../core" }
clap = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tempfile = "3"
