#!/usr/bin/env bash
set -euo pipefail

# User-level setup for muninn.
# Creates minimal muninn config if missing,
# registers and indexes the repo, and optionally restarts muninn services.
#
# Examples:
#   ./02-user-setup.sh
#   REPO_ROOT=/home/kamysh/Work/Dymium/Dev ./02-user-setup.sh
#   FORCE_CONFIG=1 ./02-user-setup.sh
#   RESTART_SERVICES=1 ./02-user-setup.sh

REPO_ROOT="${REPO_ROOT:-$(pwd)}"
REPO_NAME="${REPO_NAME:-$(basename "$REPO_ROOT")}"

DBHOST="${DBHOST:-localhost}"
DBPORT="${DBPORT:-5450}"
DBNAME="${DBNAME:-muninn}"
DBUSER="${DBUSER:-muninn}"

SCAN_DEPTH="${SCAN_DEPTH:-5}"
SCAN_ROOT="${SCAN_ROOT:-$REPO_ROOT}"

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/muninn"
CONFIG_FILE="${CONFIG_DIR}/config.toml"
FORCE_CONFIG="${FORCE_CONFIG:-0}"
RESTART_SERVICES="${RESTART_SERVICES:-0}"

mkdir -p "$CONFIG_DIR"

if [[ ! -f "$CONFIG_FILE" || "$FORCE_CONFIG" == "1" ]]; then
  cat > "$CONFIG_FILE" <<EOF
# ~/.config/muninn/config.toml — generated by 02-user-setup.sh

[database]
host   = "${DBHOST}"
port   = ${DBPORT}
dbname = "${DBNAME}"
user   = "${DBUSER}"

[embeddings]
backend    = "local"
model      = "potion-base-32M"
cache_dir  = "${HOME}/.cache/muninn/models"
batch_size = 16

[watcher]
debounce_ms = 300

[indexer]
scan_roots = ["${SCAN_ROOT}"]
scan_depth = ${SCAN_DEPTH}
EOF
  echo "Wrote ${CONFIG_FILE}"
else
  echo "Config exists at ${CONFIG_FILE} (set FORCE_CONFIG=1 to overwrite)"
fi

echo "Registering repo (if not already registered)"
EDITOR=true muninn register "$REPO_ROOT" --name "$REPO_NAME" || true

echo "Indexing repo (foreground)"
muninn index "$REPO_ROOT"

if [[ "$RESTART_SERVICES" == "1" ]]; then
  echo "Restarting muninn-index.service"
  systemctl --user restart muninn-index.service || true
  echo "Stopping any running muninn-mcp"
  pkill -f muninn-mcp || true
fi

echo "Done."
